# Generated by Django 5.2.4 on 2025-07-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpwebsiteapp', '0002_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
