# Generated by Django 5.2.4 on 2025-07-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpwebsiteapp', '0004_event_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
