# Generated by Django 5.2.4 on 2025-07-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpwebsiteapp', '0006_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('health', 'Health'), ('digital', 'Digital'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
