# Generated by Django 5.2.4 on 2025-07-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpwebsiteapp', '0009_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
    ]
