# Generated by Django 5.2.4 on 2025-07-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpwebsiteapp', '0010_remove_testimonial_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part_one', models.CharField(max_length=200)),
                ('title_part_two', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('button_primary_text', models.CharField(default='Learn More', max_length=100)),
                ('button_primary_url', models.URLField(default='/about/')),
                ('button_secondary_text', models.CharField(default='Join Us', max_length=100)),
                ('button_secondary_url', models.URLField(default='#join-section')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
