# Generated by Django 5.2.4 on 2025-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpwebsiteapp', '0012_highlightslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='button_primary_url',
            field=models.CharField(default='/about/', max_length=200),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_secondary_url',
            field=models.CharField(default='#join-section', max_length=200),
        ),
    ]
