# Generated by Django 5.2.4 on 2025-08-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpwebsiteapp', '0013_alter_heroslide_button_primary_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ict', 'ICT'), ('healthcare', 'Healthcare'), ('social_inclusion', 'Social Inclusion'), ('education', 'Education'), ('youth_women', 'Youth and Women'), ('security', 'Security'), ('lands', 'Lands'), ('infrastructure', 'Infrastructure'), ('food_security', 'Food Security'), ('energy', 'Energy'), ('ease_business', 'Ease of Doing Business'), ('huduma_centers', 'Huduma Centers')], max_length=50),
        ),
    ]
