# Generated by Django 5.2.4 on 2025-08-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpwebsiteapp', '0014_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
