# Generated by Django 5.2.4 on 2025-08-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpwebsiteapp', '0015_project_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='concern',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
