# Generated by Django 5.2.4 on 2025-08-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpwebsiteapp', '0017_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='categories',
            field=models.ManyToManyField(related_name='news_items', to='jpwebsiteapp.category'),
        ),
    ]
